coincap:
  api:
    url: "https://api.coincap.io/v2"
    key: "0e455683-e957-4d94-ae86-fcf4a3d1f1ce"

# Database configs
spring:
  application:
    name: crypto-wallet
  datasource:
    url: jdbc:h2:mem:walletdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Logging Configs
logging:
  level:
    com.postfinance.cryptowallet: INFO #DEBUG
    org.springframework: INFO
    org.hibernate:
        SQL: INFO #DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Server properties
server:
  port: 8080

# cron properties:
wallet:
  update:
    interval: 30000
    threads: 3